#!/usr/bin/env bash
# =============================================================================
# NaijasPride — Blue/Green Zero-Downtime Deploy
# =============================================================================
# How it works:
#   Two stacks (blue/green) run side by side on different ports.
#   New code builds on the INACTIVE stack while ACTIVE keeps serving.
#   Once the new build passes health checks, Nginx switches instantly.
#   Old stack stays stopped (not deleted) — rollback is one command.
#
# Usage:
#   ./deploy.sh              # full blue/green deploy
#   ./deploy.sh --rollback   # instantly revert to previous stack
#   ./deploy.sh --status     # show which stack is active
#   ./deploy.sh --logs       # deploy then tail logs
# =============================================================================
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
STATE_FILE="$APP_DIR/.deploy-state"
BLUE_PORT=3001
GREEN_PORT=3002
HEALTH_PATH="/api/v1/health"
HEALTH_RETRIES=24      # 24 × 5s = 2 min max
HEALTH_INTERVAL=5

ROLLBACK=false
TAIL_LOGS=false
STATUS_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --rollback) ROLLBACK=true ;;
    --logs)     TAIL_LOGS=true ;;
    --status)   STATUS_ONLY=true ;;
  esac
done

cd "$APP_DIR"

# ── Helpers ──────────────────────────────────────────────────────────────────
active_stack()   { [ -f "$STATE_FILE" ] && cat "$STATE_FILE" || echo "blue"; }
inactive_stack() { [ "$(active_stack)" = "blue" ] && echo "green" || echo "blue"; }
stack_port()     { [ "$1" = "blue" ] && echo "$BLUE_PORT" || echo "$GREEN_PORT"; }
compose_file()   { echo "$APP_DIR/docker-compose.$1.yml"; }

health_check() {
  local port="$1"
  echo "    Checking http://localhost:$port$HEALTH_PATH"
  for i in $(seq 1 $HEALTH_RETRIES); do
    if curl -sf "http://localhost:$port$HEALTH_PATH" >/dev/null 2>&1; then
      echo "    Health check passed!"
      return 0
    fi
    echo "    Attempt $i/$HEALTH_RETRIES — waiting ${HEALTH_INTERVAL}s..."
    sleep "$HEALTH_INTERVAL"
  done
  return 1
}

update_nginx() {
  local port="$1"
  if [ -f /etc/nginx/sites-enabled/naijaspride ]; then
    sudo sed -i "s|proxy_pass http://localhost:[0-9]*|proxy_pass http://localhost:$port|g" \
      /etc/nginx/sites-enabled/naijaspride
    sudo nginx -t -q && sudo nginx -s reload
    echo "    Nginx reloaded → port $port"
  else
    echo "    Nginx not configured yet — API available at http://$(hostname -I | awk '{print $1}'):$port"
    echo "    Run scripts/setup-nginx.sh to configure the reverse proxy."
  fi
}

generate_compose() {
  local stack="$1"
  local port
  port=$(stack_port "$stack")
  cat > "$(compose_file "$stack")" <<COMPOSE
# Auto-generated by deploy.sh — do not edit
# Stack: $stack | Port: $port
services:
  redis-$stack:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    volumes:
      - redis_data_$stack:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  flaresolverr-$stack:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: \${FLARESOLVERR_LOG_LEVEL:-info}
      TZ: \${TZ:-Africa/Lagos}

  api-$stack:
    image: naijaspride-api:$stack
    restart: unless-stopped
    depends_on:
      redis-$stack:
        condition: service_healthy
    ports:
      - "$port:3000"
    env_file: .env
    environment:
      PORT: "3000"
      REDIS_URL: redis://redis-$stack:6379
      FLARESOLVERR_URL: http://flaresolverr-$stack:8191
      TORRENT_DOWNLOAD_DIR: /tmp/naijaspride/torrent-downloads
      FFMPEG_PATH: /usr/bin/ffmpeg

  torrent-worker-$stack:
    image: naijaspride-api:$stack
    restart: unless-stopped
    command: ["node", "apps/api/dist/workers/torrent.worker.js"]
    depends_on:
      redis-$stack:
        condition: service_healthy
    env_file: .env
    environment:
      REDIS_URL: redis://redis-$stack:6379
      TORRENT_DOWNLOAD_DIR: /tmp/naijaspride/torrent-downloads
      FFMPEG_PATH: /usr/bin/ffmpeg
    volumes:
      - torrent_tmp_$stack:/tmp/naijaspride

  book-worker-$stack:
    image: naijaspride-api:$stack
    restart: unless-stopped
    command: ["node", "apps/api/dist/workers/book-import.worker.js"]
    depends_on:
      redis-$stack:
        condition: service_healthy
    env_file: .env
    environment:
      REDIS_URL: redis://redis-$stack:6379

  book-cover-worker-$stack:
    image: naijaspride-api:$stack
    restart: unless-stopped
    command: ["node", "apps/api/dist/workers/book-cover.worker.js"]
    depends_on:
      redis-$stack:
        condition: service_healthy
    env_file: .env
    environment:
      REDIS_URL: redis://redis-$stack:6379
      FFMPEG_PATH: /usr/bin/ffmpeg
      FLARESOLVERR_URL: http://flaresolverr-$stack:8191
    volumes:
      - torrent_tmp_$stack:/tmp/naijaspride

  remote-ingest-worker-$stack:
    image: naijaspride-api:$stack
    restart: unless-stopped
    command: ["node", "apps/api/dist/workers/remote-ingest.worker.js"]
    depends_on:
      redis-$stack:
        condition: service_healthy
    env_file: .env
    environment:
      REDIS_URL: redis://redis-$stack:6379
      TORRENT_DOWNLOAD_DIR: /tmp/naijaspride/torrent-downloads
      FFMPEG_PATH: /usr/bin/ffmpeg
    volumes:
      - torrent_tmp_$stack:/tmp/naijaspride

volumes:
  redis_data_$stack:
  torrent_tmp_$stack:
COMPOSE
}

# ── Status ───────────────────────────────────────────────────────────────────
if [ "$STATUS_ONLY" = true ]; then
  ACTIVE=$(active_stack)
  INACTIVE=$(inactive_stack)
  echo "Active:   $ACTIVE  (port $(stack_port "$ACTIVE"))"
  echo "Inactive: $INACTIVE (port $(stack_port "$INACTIVE"))"
  echo ""
  echo "=== $ACTIVE ==="
  docker compose -f "$(compose_file "$ACTIVE")" ps 2>/dev/null || echo "(not running)"
  exit 0
fi

# ── Rollback ─────────────────────────────────────────────────────────────────
if [ "$ROLLBACK" = true ]; then
  CURRENT=$(active_stack)
  PREVIOUS=$(inactive_stack)
  PREV_PORT=$(stack_port "$PREVIOUS")
  echo "==> Rolling back: $CURRENT → $PREVIOUS"

  # Restart previous stack if it's stopped
  docker compose -f "$(compose_file "$PREVIOUS")" up -d --remove-orphans

  if ! health_check "$PREV_PORT"; then
    echo "ERROR: Previous stack ($PREVIOUS) is not healthy. Manual intervention required."
    exit 1
  fi

  update_nginx "$PREV_PORT"
  echo "$PREVIOUS" > "$STATE_FILE"

  echo ""
  echo "==> Rolled back to $PREVIOUS (port $PREV_PORT)"
  echo "    Stopping broken stack ($CURRENT)..."
  docker compose -f "$(compose_file "$CURRENT")" stop || true
  exit 0
fi

# ── Preflight ────────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  echo "ERROR: .env not found. Run: cp .env.example .env && nano .env"
  exit 1
fi

# Ensure sudo access (needed for nginx reload)
if [ "$(id -u)" -ne 0 ] && ! sudo -n true 2>/dev/null; then
  echo "WARNING: Deploy may need sudo for nginx operations."
  echo "         If the switch fails, re-run with: sudo ./deploy.sh"
fi

# ── Deploy ───────────────────────────────────────────────────────────────────
ACTIVE=$(active_stack)
INACTIVE=$(inactive_stack)
INACTIVE_PORT=$(stack_port "$INACTIVE")

echo ""
echo "============================================"
echo "  NaijasPride Deploy"
echo "  Current active: $ACTIVE (port $(stack_port "$ACTIVE"))"
echo "  Building:       $INACTIVE (port $INACTIVE_PORT)"
echo "============================================"

echo ""
echo "==> Pulling latest code"
git fetch --all --prune
git reset --hard origin/main

echo ""
echo "==> Generating compose files"
generate_compose blue
generate_compose green

echo ""
echo "==> Removing stale image from previous cycle (naijaspride-api:$INACTIVE)"
# The $INACTIVE stack has been stopped since last deploy. Its image is now
# two cycles old — we're about to overwrite it anyway, so remove it first
# to reclaim disk space before the new build.
docker rmi "naijaspride-api:$INACTIVE" 2>/dev/null && echo "    Removed old naijaspride-api:$INACTIVE" || echo "    No stale image to remove"

echo ""
echo "==> Building image: naijaspride-api:$INACTIVE"
docker build -t "naijaspride-api:$INACTIVE" .

echo ""
echo "==> Running database migrations"
docker run --rm \
  --env-file .env \
  "naijaspride-api:$INACTIVE" \
  npx prisma migrate deploy --schema apps/api/prisma/schema.prisma

echo ""
echo "==> Starting $INACTIVE stack"
docker compose -f "$(compose_file "$INACTIVE")" up -d --remove-orphans

echo ""
echo "==> Health checking new stack"
if ! health_check "$INACTIVE_PORT"; then
  echo ""
  echo "ERROR: New stack ($INACTIVE) failed health check. Aborting."
  echo "Logs:"
  docker compose -f "$(compose_file "$INACTIVE")" logs --tail=80 "api-$INACTIVE" 2>/dev/null || true
  docker compose -f "$(compose_file "$INACTIVE")" down
  exit 1
fi

echo ""
echo "==> Switching traffic to $INACTIVE"
update_nginx "$INACTIVE_PORT"
echo "$INACTIVE" > "$STATE_FILE"

echo ""
echo "==> Stopping old stack ($ACTIVE)"
docker compose -f "$(compose_file "$ACTIVE")" stop || true
# naijaspride-api:$ACTIVE image is intentionally kept — it's needed for
# rollback. It will be removed at the start of the NEXT deploy cycle.

echo ""
echo "==> Pruning build cache and dangling images"
# Build cache grows ~2-5 GB per deploy. Always safe to prune here because
# the final image layers are already written to disk in the new image.
docker builder prune -f
docker image prune -f

echo ""
echo "============================================"
echo "  Deploy complete!"
echo "  Active: $INACTIVE (port $INACTIVE_PORT)"
echo "  Rollback: ./deploy.sh --rollback"
echo "============================================"
docker compose -f "$(compose_file "$INACTIVE")" ps

if [ "$TAIL_LOGS" = true ]; then
  echo ""
  echo "==> Tailing logs (Ctrl+C to stop)"
  docker compose -f "$(compose_file "$INACTIVE")" logs -f
fi
